name: Android APK (Capacitor)
on:
  workflow_dispatch:
  push:
    branches: [ pulseo-monolith, main, master, pulseo-first-test, pulseo-sante-v1 ]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: android-actions/setup-android@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - name: Install deps
        run: |
          (pnpm -v >/dev/null 2>&1 && pnpm i) || npm i
          if [ -f apps/mobile/package.json ]; then (pnpm -C apps/mobile i || npm --prefix apps/mobile i); fi
      - name: Restore keystore (if secrets provided)
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          bash scripts/decode-keystore.sh || true
      - name: Build web + Capacitor sync
        run: |
          if [ -f apps/mobile/package.json ]; then (pnpm -C apps/mobile build || npm --prefix apps/mobile run build); fi
          npx cap sync android --root apps/mobile || true
      - name: Assemble APK (release → debug fallback)
        run: |
          cd apps/mobile/android
          ./gradlew assembleRelease --stacktrace || ./gradlew assembleDebug --stacktrace
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pulseo-APK
          path: |
            apps/mobile/android/app/build/outputs/apk/release/*.apk
            apps/mobile/android/app/build/outputs/apk/debug/*.apk
