name: Deploy Pulseo to OVH
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - name: Install & Build
        run: |
          npm ci
          npm run build
          tar -czf artefact.tgz .next public package.json package-lock.json ecosystem.config.js
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Ship artefact to VPS
        env: { HOST: ${{ secrets.OVH_HOST }}, USER: ${{ secrets.OVH_USER }}, PATH_DIR: ${{ secrets.OVH_PATH }} }
        run: |
          set -e
          TS=$(date +%Y%m%d%H%M%S)
          ssh -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p $PATH_DIR/releases/$TS"
          scp -o StrictHostKeyChecking=no artefact.tgz $USER@$HOST:$PATH_DIR/releases/$TS/artefact.tgz
      - name: Deploy & restart on VPS
        env: { HOST: ${{ secrets.OVH_HOST }}, USER: ${{ secrets.OVH_USER }}, PATH_DIR: ${{ secrets.OVH_PATH }} }
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST '
            set -e
            APP=pulseo; DIR='"${{ secrets.OVH_PATH }}"'; PORT=3000
            sudo apt-get update -y >/dev/null 2>&1 || true
            command -v pm2 >/dev/null 2>&1 || sudo npm i -g pm2
            sudo mkdir -p "$DIR/releases" "$DIR/current"
            sudo chown -R '"${{ secrets.OVH_USER }}"':'"${{ secrets.OVH_USER }}"' "$DIR"
            cd "$DIR/releases" && LAST=$(ls -1 | sort -r | head -n1)
            cd "$DIR/releases/$LAST"
            tar -xzf artefact.tgz
            ln -sfn "$DIR/releases/$LAST" "$DIR/current"
            cd "$DIR/current"
            pm2 startOrReload ecosystem.config.js || pm2 start node_modules/next/dist/bin/next --name "$APP" -- start -p "$PORT"
            pm2 save || true
            # Nginx proxy minimal si besoin
            if [ ! -f /etc/nginx/sites-available/pulseo ]; then
              sudo tee /etc/nginx/sites-available/pulseo >/dev/null <<CONF
server {
  listen 80;
  server_name _;
  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Proto \$scheme;
  }
}
CONF
              sudo ln -sf /etc/nginx/sites-available/pulseo /etc/nginx/sites-enabled/pulseo
              sudo rm -f /etc/nginx/sites-enabled/default || true
            fi
            sudo nginx -t && sudo systemctl reload nginx || true
          '
      - name: Healthcheck public
        env: { HOST: ${{ secrets.OVH_HOST }} }
        run: curl -fsSI http://$HOST/ | head -n1
